---
title: "RLadiesMX2020"
subtitle: "Primer Encuentro Anual R-Ladies México"
date: "`r Sys.time()`"
params:
    hashtag: "#RLadiesMX"
    # Times
    start_day: "2020-09-24"
    end_day: "2020-09-24"
    timezone: "America/New_York"
    # Plot theme and colours
    theme: "theme_light"
    accent: "#88398a"
    accent2: "#a7a9ac"
    # Analysis parameters
    kcore: 2
    topics_k: 6
    bigram_filter: 3
    # Dataset fixed, set true to stop adding new tweets
    fixed: TRUE
    # Random seed
    seed: 1
---

```{r knitr, include = FALSE}
DOCNAME <- tools::file_path_sans_ext(knitr::current_input())
knitr::opts_chunk$set(
    echo           = FALSE,
    error          = FALSE,
    fig.align      = "center",
    fig.path       = paste0("figures/", DOCNAME, "/"),
    fig.width      = 10,
    fig.height     = 8,
    message        = FALSE,
    warning        = FALSE
)
```

```{r libraries, include = FALSE}
# Twitter
library("rtweet")
# Data manipulation
library("dplyr")
library("tidyr")
library("lubridate")
library("forcats")
library("purrr")
library("stringr")
# Networks
library("igraph")
# Text analysis
library("tidytext")
library("topicmodels")
# Visualisation
library("ggplot2")
library("ggrepel")
library("ggraph")
library("wordcloud")
library("viridis")
# Images
library("webshot")
library("magick")
# Presentation
library("knitr")
library("kableExtra")
# File paths
library("here")
library("fs")
```

**Parameters**

```{r params}
params_table <- data.frame(Parameter = names(params), Value = unlist(params))
kable(params_table, row.names = FALSE) %>% kable_styling()
```

```{r load}
data_file <- here("data", paste0(DOCNAME, ".Rds"))
if (params$fixed) {
    if (file_exists(data_file)) {
        tweets <- readRDS(data_file)
    } else {
        stop("fixed is TRUE but no data file exists", call. = FALSE)
    }
} else {
    if (file_exists(data_file)) {
        existing_tweets <- readRDS(data_file)
        message(nrow(existing_tweets), " tweets already downloaded")

        new_tweets <- search_tweets(params$hashtag, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(new_tweets), " tweets")

        tweets <- new_tweets %>%
            rbind(existing_tweets) %>%
            group_by(status_id) %>%
            top_n(1, collected_at) %>%
            ungroup()
        message("Dataset now contains ", nrow(tweets), " tweets")
    } else {
        tweets <- search_tweets(params$hashtag, 10000) %>%
            mutate(collected_at = Sys.time())
        message("Found ", nrow(tweets), " tweets")
    }
    saveRDS(tweets, data_file)
}

tweets <- tweets %>%
    mutate(
        date = as_date(created_at, tz = params$timezone),
        datetime = as_datetime(created_at, tz = params$timezone),
        hour = hour(datetime)
    )
```

# Introduction

An analysis of tweets from the `r params$hashtag` hashtag for the
[RLadiesMX 2020 online event][RLadiesMX2020],
September 24, 2020.

Este es un análsis de los tweets de la etiqueta `r params$hashtag` para el
[evento RLadiesMX 2020][RLadiesMX2020],
del 24 de septiembre del 2020 que se llevó acabo en línea.

```{r analysis, child = "_analysis.Rmd"}
# This chunk adds the template analysis
```

# Session info {.unnumbered}

```{r session-info}
sessionInfo()
```

[RLadiesMX2020]: https://rladiesmx.netlify.app/talk/2020-08-23-encuentro2020/ "Primer Encuentro Anual R-Ladies México"
